# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_cleaning_agent
# Time Created: 2025-02-08 08:05:03

def data_cleaner(data_raw):
    import pandas as pd
    import numpy as np


    # Step 1: Check for Missing Values
    # No columns are removed because there are no missing values.

    # Step 2: Convert Data Types
    # Convert the TotalCharges column from object to float64
    data_raw['TotalCharges'] = pd.to_numeric(data_raw['TotalCharges'], errors='coerce')
    # Comment: This step converts TotalCharges to a numeric type for better analysis.

    # Step 3: Remove Duplicate Rows
    data_raw.drop_duplicates(inplace=True)
    # Comment: This ensures that each customer record is unique.

    # Step 4: Impute Missing Values (if applicable)
    # No missing value imputation is performed as all values are present.

    # Step 5: Remove Rows with Missing Values (if applicable)
    # No rows are removed since there are no missing values.

    # Step 6: Check for Outliers
    # Note: Outliers are not removed, but could be flagged for further analysis.
    
    # Step 7: Analyze Data for Additional Cleaning Needs
    # We will review unique value counts in categorical columns later if needed.

    # Step 8: Final Review and Export Data
    # Confirm transformations are documented.
    
    # Return the cleaned data
    return data_raw